# Name of the workflow
name: 'CI/CD'

# Trigger the workflow on push events to the main branch or master branch
on:
  push:
    branches:
      - main

# Define the jobs to be run in the workflow
jobs:
  # Job to build the application
  build:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest
    # Set the environment variable CI to false
    env:
      CI: false
    # Define the steps to be run in the job
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js with version 14
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install the dependencies for the application
    - name: Install dependencies
      run: npm install

    # Build the application
    - name: Build
      run: npm run build